import { notFound } from 'next/navigation';
import { WorkoutFeedbackPanel } from '@/components/academy/WorkoutFeedback';
import type { SegmentReport, SegmentVerdict } from '@/lib/academy/segments';

// ── Login-free preview of the mentor's weekly review screen ─────────────────
//
// The real screen lives inside the staff academy tab, which needs a session, a
// staff flag, and a trainee who actually ran the session being graded. That is
// three things to line up before anyone can look at the layout — so this route
// renders the SAME component against fixed data, on a URL that needs no login
// and works from a phone.
//
// Development only: it renders one athlete's feedback UI with no auth around it,
// and while the fixtures are invented, the save button posts to the real API. In
// production the route does not exist.
//
// Two things are deliberately not faked: the component is the real one (so a
// layout bug here is a layout bug there), and the Hebrew is generated by the real
// renderer rather than typed into the fixture.

export const dynamic = 'force-dynamic';

/** A step as the grader emits it. Defaults keep the fixtures down to what matters. */
function seg(over: Partial<SegmentVerdict> & { index: number; label: string }): SegmentVerdict {
  return {
    type: 'interval',
    plannedPaceMin: null, plannedPaceMax: null, actualPace: null, actualDistanceM: null,
    status: 'unknown', graded: false, metric: 'none',
    plannedHrMin: null, plannedHrMax: null, actualHr: null,
    ...over,
  };
}

function report(segments: SegmentVerdict[]): SegmentReport {
  const graded = segments.filter(s => s.graded || (s.metric === 'hr' && !s.hrUngradedReason));
  return {
    aligned: true,
    segments,
    gradedCount: graded.length,
    onTargetCount: graded.filter(s => s.status === 'on_target').length,
  };
}

// ── Case 1: a pace session, run the way athletes actually run them ──
// Opens 12 sec/km under the band and gives it all back by the last rep. This is the
// shape the suggestion engine is for: the chips should arrive already saying
// "opened too fast" and "faded", and the mentor's job is to confirm it.
const PACE = report([
  seg({ index: 0, type: 'warmup', label: 'חימום 2km', actualPace: 320, actualDistanceM: 2000 }),
  seg({ index: 1, label: 'חזרה 1km', graded: true, metric: 'pace',
        plannedPaceMin: 240, plannedPaceMax: 246, actualPace: 228, actualDistanceM: 1000, status: 'faster' }),
  seg({ index: 2, type: 'recovery', label: 'התאוששות 2min', actualPace: 400, actualDistanceM: 400 }),
  seg({ index: 3, label: 'חזרה 1km', graded: true, metric: 'pace',
        plannedPaceMin: 240, plannedPaceMax: 246, actualPace: 233, actualDistanceM: 1000, status: 'faster' }),
  seg({ index: 4, type: 'recovery', label: 'התאוששות 2min', actualPace: 405, actualDistanceM: 400 }),
  seg({ index: 5, label: 'חזרה 1km', graded: true, metric: 'pace',
        plannedPaceMin: 240, plannedPaceMax: 246, actualPace: 244, actualDistanceM: 1000, status: 'on_target' }),
  seg({ index: 6, type: 'recovery', label: 'התאוששות 2min', actualPace: 410, actualDistanceM: 400 }),
  seg({ index: 7, label: 'חזרה 1km', graded: true, metric: 'pace',
        plannedPaceMin: 240, plannedPaceMax: 246, actualPace: 258, actualDistanceM: 1000, status: 'slower' }),
  seg({ index: 8, type: 'cooldown', label: 'שחרור 1km', actualPace: 330, actualDistanceM: 1000 }),
]);

// ── Case 2: the same session written in BEATS ──
// The whole point of the engine change. Every rep is at a good pace and every rep is
// over the prescribed heart rate, so the verdict is "did not execute" even though the
// pace column looks excellent. The target column is HR, and the words change with it.
const HR_BPM = report([
  seg({ index: 0, type: 'warmup', label: 'חימום 2km', actualPace: 325, actualDistanceM: 2000 }),
  seg({ index: 1, label: 'בלוק 2km', metric: 'hr', graded: false,
        plannedHrMin: 148, plannedHrMax: 152, actualHr: 168,
        actualPace: 252, actualDistanceM: 2000, status: 'faster' }),
  seg({ index: 2, type: 'recovery', label: 'התאוששות 3min', actualPace: 420, actualDistanceM: 600 }),
  seg({ index: 3, label: 'בלוק 2km', metric: 'hr', graded: false,
        plannedHrMin: 148, plannedHrMax: 152, actualHr: 171,
        actualPace: 254, actualDistanceM: 2000, status: 'faster' }),
  seg({ index: 4, type: 'cooldown', label: 'שחרור 1km', actualPace: 335, actualDistanceM: 1000 }),
]);

// ── Case 3: an HR target written as a PERCENTAGE, with no anchor stored ──
// 75-80% of what? Nothing in the app knew until athletes.max_hr_bpm existed, and it is
// empty until it is filled per athlete. This is what the screen says instead of
// grading the step against a guessed band.
const HR_NO_ANCHOR = report([
  seg({ index: 0, type: 'warmup', label: 'חימום 2km', actualPace: 330, actualDistanceM: 2000 }),
  seg({ index: 1, label: 'בלוק 5km', metric: 'hr', hrUngradedReason: 'no_anchor',
        actualHr: 154, actualPace: 268, actualDistanceM: 5000, status: 'unknown' }),
  seg({ index: 2, type: 'cooldown', label: 'שחרור 1km', actualPace: 340, actualDistanceM: 1000 }),
]);

const CASES: { title: string; note: string; name: string; report: SegmentReport }[] = [
  {
    title: 'אימון שנכתב בקצב',
    note: 'פתח 12 שניות מתחת לטווח וסיים 12 מעליו. הצ׳יפים אמורים להגיע מסומנים: פתיחה מהירה מדי, דעיכה.',
    name: '4×1000 מ׳ בקצב סף',
    report: PACE,
  },
  {
    title: 'אותו אימון, אבל נכתב בדופק',
    note: 'הקצב מעולה בכל בלוק, הדופק גבוה מהיעד בכל בלוק — ולכן האימון לא בוצע. עמודת היעד היא דופק, והמילים משתנות בהתאם.',
    name: '2×2000 מ׳ בדופק 150',
    report: HR_BPM,
  },
  {
    title: 'יעד דופק באחוזים, בלי דופק מקסימלי שמור',
    note: 'אין נגד מה לדרג, ולכן המסך אומר את זה במקום להמציא טווח.',
    name: '5 ק״מ ב-75-80% מהדופק',
    report: HR_NO_ANCHOR,
  },
];

export default function AcademyFeedbackPreview() {
  if (process.env.NODE_ENV === 'production') notFound();

  return (
    <div dir="rtl" className="min-h-screen bg-page p-4">
      <div className="mx-auto max-w-[390px] space-y-6">
        <header className="pt-2">
          <h1 className="text-lg font-bold text-ink-900">מסך הפידבק השבועי</h1>
          <p className="mt-1 text-xs text-ink-400">
            תצוגה מקדימה עם נתונים לדוגמה — אותו רכיב שרץ במסך האקדמיה, בלי צורך בהתחברות.
          </p>
        </header>

        {CASES.map(c => (
          <section key={c.title} className="rounded-2xl bg-white p-3">
            <h2 className="text-sm font-bold text-ink-900">{c.title}</h2>
            <p className="mt-1 text-[11px] leading-relaxed text-ink-400">{c.note}</p>
            <p className="mt-2 text-xs font-semibold text-ink-700" dir="auto">{c.name}</p>
            <WorkoutFeedbackPanel
              athleteId="preview"
              date="2026-09-16"
              workoutName={c.name}
              report={c.report}
              mentorName="יוסי"
            />
          </section>
        ))}

        <p className="pb-8 text-[11px] text-ink-400">
          כפתור השליחה פונה ל-API האמיתי, ולכן במסך הזה הוא ייכשל בלי התחברות. כל השאר אמיתי.
        </p>
      </div>
    </div>
  );
}
